### ISSUE TITLE
DAB integration with SWA: MsSql managed identity failing to connect

### ISSUE THREAD

**Issue by Mathos1432** [Azure/data-api-builder#1127]
https://ambitious-pond-09b47ed21.1.azurestaticappscanary.net/

Azure.DataApiBuilder.Service.Exceptions.DataApiBuilderException: Cannot obtain Schema for entity Author with underlying database object source: dbo.authors due to: Login failed for user '<token-identified principal>'.
> Unable to complete runtime initialization operations due to: 
      Azure.DataApiBuilder.Service.Exceptions.DataApiBuilderException: Cannot obtain Schema for entity Author with underlying database object source: dbo.authors due to: Login failed for user '<token-identified principal>'.
         at Azure.DataApiBuilder.Service.Services.SqlMetadataProvider`3.GetTableWithSchemaFromDataSetAsync(String entityName, String schemaName, String tableName) in /src/src/Service/Services/MetadataProviders/SqlMetadataProvider.cs:line 967
         at Azure.DataApiBuilder.Service.Services.SqlMetadataProvider`3.PopulateSourceDefinitionAsync(String entityName, String schemaName, String tableName, SourceDefinition sourceDefinition, String[] runtimeConfigKeyFields) in /src/src/Service/Services/MetadataProviders/SqlMetadataProvider.cs:line 880
         at Azure.DataApiBuilder.Service.Services.SqlMetadataProvider`3.PopulateObjectDefinitionForEntities() in /src/src/Service/Services/MetadataProviders/SqlMetadataProvider.cs:line 736
         at Azure.DataApiBuilder.Service.Services.SqlMetadataProvider`3.InitializeAsync() in /src/src/Service/Services/MetadataProviders/SqlMetadataProvider.cs:line 221
         at Azure.DataApiBuilder.Service.Startup.PerformOnConfigChangeAsync(IApplicationBuilder app) in /src/src/Service/Startup.cs:line 492
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.StatusCodeResult[1]
      Executing StatusCodeResult, setting HTTP status code 200

This error is also not stopping container allocation from happening?

**Comment by Aniruddh25** [comment]
This has been fixed.
