### ISSUE TITLE
[Bug]: Unable to map primary key colum (?) - app crashes

### ISSUE THREAD

**Issue by ErikEJ** [Azure/data-api-builder#1340]
### What happened?

I am using the Chinook sample database, Album table.

I can map Title to something else, but not pk AlbumId => id

I get error 500 - and have host mode development - but get no errors

### Version

0.5.34

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

REST

### Relevant log output

```Text
"entities": {
    "Album": {
      "source": "dbo.Album",
      "permissions": [
        {
          "role": "anonymous",
          "actions": [
            "*"
          ]
        }
      ],
      "mappings": {
        "AlbumId": "id"
      }
    }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ErikEJ** [comment]
Finally got errors with 

    dab start --LogLevel Debug


```
3ec20664-26ca-4ed0-833b-f7e98fefb85f: The given key was not present in the dictionary.
failinfo: Azure.DataApiBuilder.Service.Controllers.RestController[0]
      3ec20664-26ca-4ed0-833b-f7e98fefb85f:    at System.Text.Json.JsonElement.GetProperty(String propertyName)
         at Azure.DataApiBuilder.Service.Resolvers.SqlPaginationUtil.MakeCursorFromJsonElement(JsonElement element, List`1 primaryKey, List`1 orderByColumns, String entityName, String schemaName, String tableName, ISqlMetadataProvider sqlMetadataProvider)
         at Azure.DataApiBuilder.Service.Resolvers.SqlQueryEngine.FormatFindResult(JsonDocument jsonDoc, FindRequestContext context)
         at Azure.DataApiBuilder.Service.Resolvers.SqlQueryEngine.ExecuteAsync(FindRequestContext context)
         at Azure.DataApiBuilder.Service.Services.RestService.ExecuteAsync(String entityName, Operation operationType, String primaryKeyRoute)
         at Azure.DataApiBuilder.Service.Controllers.RestController.HandleOperation(String route, Operation operationType)
: Microsoft.AspNetCore.Mvc.Infrastructure.SystemTextJsonResultExecutor[1]

```

**Comment by ErikEJ** [comment]
When is an Update planned?
