### ISSUE TITLE
[Bug]: Internal error 'Ncdc-d' is not a valid GraphQL type name (Parameter value)

### ISSUE THREAD

**Issue by diallonortv** [Azure/data-api-builder#1585]
### What happened?

Hello,
I have a test table (SQL Server 2022) with 3 lines on it, named dbo.test, there is 3 fields on it :
id int PK
Dossier varchar(500)
patient varchar(500)

My configuration for this table is the following 👍 
`"test": {
      "source": "dbo.test",
      "permissions": [
        {
          "role": "Read",
          "actions": [
            "*"
          ]
        }
      ]
    }`

When i send a graphql request with postman :

`{
    tests{
            items{
                id
            }
            hasNextPage
            endCursor
    }
}`

It throw an internal error :

icrosoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMS6P6V4M60D", Request id "0HMS6P6V4M60D:00000002": An unhandled exception was thrown by the application.
      System.ArgumentException: `Ncdc-d` is not a valid GraphQL type name. (Parameter 'value')
         at HotChocolate.NameString..ctor(String value)
         at HotChocolate.Types.Factories.ObjectTypeFactory.DeclareFields(ObjectTypeDefinition parent, IReadOnlyCollection`1 fields, Boolean preserveSyntaxNodes)
         at HotChocolate.Types.Factories.ObjectTypeFactory.Create(IDescriptorContext context, ObjectTypeDefinitionNode node)
         at HotChocolate.Types.Factories.SchemaSyntaxVisitor.VisitChildren(ObjectTypeDefinitionNode node, SchemaSyntaxVisitorContext context)
         at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(ISyntaxNode node, TContext context)
         at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit[T,P](T node, P parent, TContext context)
         at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(DocumentNode node, TContext context)
         at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(ISyntaxNode node, TContext context)
         at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit[T,P](T node, P parent, TContext context)
         at HotChocolate.SchemaBuilder.Setup.ParseDocuments(SchemaBuilder builder, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Setup.CreateTypeReferences(SchemaBuilder builder, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Azure.DataApiBuilder.Service.Authorization.ClientRoleHeaderAuthorizationMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Azure.DataApiBuilder.Service.AuthenticationHelpers.ClientRoleHeaderAuthenticationMiddleware.InvokeAsync(HttpContext httpContext)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Azure.DataApiBuilder.Service.Startup.<>c__DisplayClass11_0.<<Configure>b__3>d.MoveNext()
      --- End of stack trace from previous location ---
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Azure.DataApiBuilder.Service.Services.PathRewriteMiddleware.InvokeAsync(HttpContext httpContext)
         at Azure.DataApiBuilder.Service.Services.CorrelationIdMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

### Version

0.7.6+61de247acf65280d93783072226f695536591ffb

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

GraphQL

### Relevant log output

```Text
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMS6P6V4M60H", Request id "0HMS6P6V4M60H:00000002": An unhandled exception was thrown by the application.
      System.ArgumentException: `Ncdc-d` is not a valid GraphQL type name. (Parameter 'value')
         at HotChocolate.NameString..ctor(String value)
         at HotChocolate.Types.Factories.ObjectTypeFactory.DeclareFields(ObjectTypeDefinition parent, IReadOnlyCollection`1 fields, Boolean preserveSyntaxNodes)
         at HotChocolate.Types.Factories.ObjectTypeFactory.Create(IDescriptorContext context, ObjectTypeDefinitionNode node)
         at HotChocolate.Types.Factories.SchemaSyntaxVisitor.VisitChildren(ObjectTypeDefinitionNode node, SchemaSyntaxVisitorContext context)
         at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(ISyntaxNode node, TContext context)
         at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit[T,P](T node, P parent, TContext context)
         at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(DocumentNode node, TContext context)
         at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(ISyntaxNode node, TContext context)
         at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit[T,P](T node, P parent, TContext context)
         at HotChocolate.SchemaBuilder.Setup.ParseDocuments(SchemaBuilder builder, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Setup.CreateTypeReferences(SchemaBuilder builder, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Azure.DataApiBuilder.Service.Authorization.ClientRoleHeaderAuthorizationMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Azure.DataApiBuilder.Service.AuthenticationHelpers.ClientRoleHeaderAuthenticationMiddleware.InvokeAsync(HttpContext httpContext)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Azure.DataApiBuilder.Service.Startup.<>c__DisplayClass11_0.<<Configure>b__3>d.MoveNext()
      --- End of stack trace from previous location ---
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Azure.DataApiBuilder.Service.Services.PathRewriteMiddleware.InvokeAsync(HttpContext httpContext)
         at Azure.DataApiBuilder.Service.Services.CorrelationIdMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
Hi @diallonortv,

I was unable to reproduce the issue with the details you provided. 

Is `Ncdc-d` a column name of a different table/different entity defined in your runtime config?

If so, that column name would need to be aliased since the dash "-" is not an allowed character in GraphQL names as the error suggests: [GraphQL Sped](https://www.apollographql.com/docs/apollo-server/schema/schema/#naming-conventions) (Regex: `/[_A-Za-z][_0-9A-Za-z]*`

For the entity which contains the field `Ncdc-d`, you would need to add the following configuration property for the entity with the format `"<db_colum_name": "<mapped_alias_name>"`:
```json
"mappings": {
    "Ncdc-d": "<New_name>"
  }
```

See more in this doc section: https://learn.microsoft.com/azure/data-api-builder/configuration-file#mappings

I also see you are defining permissions for the custom role `Read`. Have you provided the HTTP header `X-MS-API-ROLE` with the value `Read` in your POST request? That header is required when you want the request to be evaluated in the context of non-system roles. [System roles are defined as anonymous/authenticated](https://learn.microsoft.com/azure/data-api-builder/authorization#roles).

**Comment by diallonortv** [comment]
Thanks a lot ! You are right one of the field on my other entity (Pre) had a "-" therefore did mess it up althought it wasn't the entity i was querying (test).

Regards

Vincent

**Comment by diallonortv** [comment]
Thanks
