### ISSUE TITLE
[Bug]: using multiple filters on a nested object field returns an access forbidden message

### ISSUE THREAD

**Issue by dgcaron** [Azure/data-api-builder#1624]
### What happened?

The changes have been made according to the remarks made in #1538 this works well when the query looks like this:

```gql
{
    assets(
      filter: {
        and: [
          { type: { eq: "asset" } }
          { collection: { eq: $domain } }
          { data: { container: { neq: $domain } } }
         ]
      }
    ) {
      items {
        __typename
        ...AssetFields
      }
    }
  }
```

however when i use multiple filters on the nested object the access forbidden error is returned

```gql
{
    assets(
      filter: {
        and: [
          { type: { eq: "asset" } }
          { collection: { eq: $domain } }
          { data: { container: { neq: $domain } } }
          { data: { path: { notContains: ".json" } } }
        ]
      }
    ) {
      items {
        __typename
        ...AssetFields
      }
    }
  }
```

### Version

0.7.6 (part of the swa cli)

### What database are you using?

CosmosDB NoSQL

### What hosting model are you using?

Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

GraphQL

### Relevant log output

```Text
dataApi] fail: Azure.DataApiBuilder.Service.Startup[0]
[dataApi]          at Azure.DataApiBuilder.Service.Models.GQLFilterParser.Parse(IMiddlewareContext ctx, IInputField filterArgumentSchema, List`1 fields, BaseQueryStructure queryStructure) in /_/src/Service/Models/GraphQLFilterParsers.cs:line 159
[dataApi]          at Azure.DataApiBuilder.Service.Models.GQLFilterParser.ParseAndOr(IMiddlewareContext ctx, IInputField argumentSchema, IInputField filterArgumentSchema, List`1 fields, BaseQueryStructure baseQuery, PredicateOperation op) in /_/src/Service/Models/GraphQLFilterParsers.cs:line 430
[dataApi]          at Azure.DataApiBuilder.Service.Models.GQLFilterParser.Parse(IMiddlewareContext ctx, IInputField filterArgumentSchema, List`1 fields, BaseQueryStructure queryStructure) in /_/src/Service/Models/GraphQLFilterParsers.cs:line 56
[dataApi]          at Azure.DataApiBuilder.Service.Resolvers.CosmosQueryStructure.Init(IDictionary`2 queryParams) in /_/src/Service/Resolvers/CosmosQueryStructure.cs:line 168
[dataApi]          at Azure.DataApiBuilder.Service.Resolvers.CosmosQueryEngine.ExecuteAsync(IMiddlewareContext context, IDictionary`2 parameters) in /_/src/Service/Resolvers/CosmosQueryEngine.cs:line 64
[dataApi]          at Azure.DataApiBuilder.Service.Services.ResolverMiddleware.InvokeAsync(IMiddlewareContext context) in /_/src/Service/Services/ResolverMiddleware.cs:line 146
[dataApi]          at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
[dataApi]          at HotChocolate.AspNetCore.Authorization.AuthorizeMiddleware.InvokeAsync(IDirectiveContext context)
[dataApi]          at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
[dataApi]          at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
[dataApi]          at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aniruddh25** [comment]
hi @dgcaron, thank you for reporting. We will investigate.

In the meantime - could you please try adding include: "*" to the read permission of the nested AssetData entity as follows:
```
    "AssetData": {
      "source": "Asset",
      "permissions": [
        {
          "actions": [
            {
              "action": "read",
               "fields": {
                         "include": ["*" ]
                  }
            }
          ],
          "role": "anonymous"
        }
      ]
    }
```

**Comment by tarazou9** [comment]
@dgcaron Thank you for reporting! As a work around, please use the filter as below, this should work and serve the purpose for your use case. In the meanwhile, we are investigating into this. 
```
{
    assets(
      filter: {
        and: [
          { type: { eq: "asset" } }
          { collection: { eq: $domain } }
          { data: {
              and: [
                  { container: { neq: $domain }} 
                  { path: { notContains: ".json" }}
                ]
           } 
        }]
      }
    ) {
      items {
        __typename
        ...AssetFields
      }
    }
  }
```
