### ISSUE TITLE
[Bug]: "The object type `Query` has to at least define one field in order to be valid. (HotChocolate.Types.ObjectType)"

### ISSUE THREAD

**Issue by yorek** [Azure/data-api-builder#1740]
### What happened?

If a stored procedure doesn't return any resultset, like this one:

```sql
create procedure dbo.stpDummy
as
print 'This is dummy'
go
```

and that stored procedure is used in DAB configuration file, for example:

```json
"entities": {
    "Dummy": {
      "source": {
        "object": "dbo.stpDummy",
        "type": "stored-procedure"       
      },
      "permissions": [
        {
          "role": "anonymous",
          "actions": [ "*" ]
        }
      ]
    }   
  }
```

when trying to access the `/graphql` endpoint, the exception 
```
"The object type `Query` has to at least define one field in order to be valid. (HotChocolate.Types.ObjectType)" 
```
will be generated and no GraphQL schema will be available.

I think there are two options to solve this.

Option 1: a warning is generated in the log output, static that such stored procedure will not be available in GraphQL as no schema is returned. The stored procedure is node made available in the GraphQL endpoint
Option 2: maybe there is an option to tell GraphQL that there is really nothing returned so that we can avoid the error altogheter?

**Note** that with REST everything works just fine (including the OpenAPI and Swagger support)

### Version

Microsoft.DataApiBuilder 0.8.51+9b0304e790689b2604ce40803cd088d1adaf0694

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

GraphQL

### Relevant log output

```Text
Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMTQQOMKE8LK", Request id "0HMTQQOMKE8LK:00000003": An unhandled exception was thrown by the application.
      HotChocolate.SchemaException: For more details look at the `Errors` property.

      1. The object type `Query` has to at least define one field in order to be valid. (HotChocolate.Types.ObjectType)

         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Azure.DataApiBuilder.Core.Authorization.ClientRoleHeaderAuthorizationMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Azure.DataApiBuilder.Core.AuthenticationHelpers.ClientRoleHeaderAuthenticationMiddleware.InvokeAsync(HttpContext httpContext)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Azure.DataApiBuilder.Service.Startup.<>c__DisplayClass10_0.<<Configure>b__3>d.MoveNext()
      --- End of stack trace from previous location ---
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Azure.DataApiBuilder.Core.Services.PathRewriteMiddleware.InvokeAsync(HttpContext httpContext)
         at Azure.DataApiBuilder.Core.Services.CorrelationIdMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yorek** [comment]
I did other tests and it seems that the problem is with stored procedures in general. I tested this stored procedure:

```sql
create or alter procedure dbo.stp_Dummy2
as
select * from (values(10,20),(30,40)) as t (col1, col2)
go  
```

with this configuration:

```json
"Dummy2": {
      "source": {
        "type": "stored-procedure",
        "object": "dbo.stp_Dummy2"
      },
      "permissions": [
        {
          "role": "anonymous",
          "actions": [
            "execute"
          ]
        }
      ]
    }
```
and have the same issue.

**Comment by seantleonard** [comment]
Issue, by design, but can be updated in docs:
- GraphQL Schemas require at least one field (query) in the root Query field. When you define one entity in the DAB config and it is a stored procedure, stored procedures default to mutations. This will result in a failure to generate a GraphQL schema.
- Explicitly set the single stored procedure entity to be generated in the GraphQL schema as a `query`:
```json
     "graphql": {
       "operation": "query"
     }
```

The following entities section configuration works as intended because at least one of the entities is defined as a `query`:
```json
 "entities": {
   "Dummy2": {
     "source": {
       "type": "stored-procedure",
       "object": "dbo.stp_Dummy2"
     },
     "graphql": {
       "operation": "mutation"
     },
     "permissions": [
       {
         "role": "anonymous",
         "actions": [
           "execute"
         ]
       }
     ]
   },
   "Dummy3": {
     "source": {
       "type": "stored-procedure",
       "object": "dbo.stp_Dummy2"
     },
     "graphql": {
       "operation": "query"
     },
     "permissions": [
       {
         "role": "anonymous",
         "actions": [
           "execute"
         ]
       }
     ]
   }
 }
```

The following query/mutation can be used:

```graphql
query execDummy3QuerySP {
  executeDummy3{
    col1
    col2
  }
}

mutation execDummy2MutationSP {
  executeDummy2 {
    col1
    col2
  }
}
```

Result:
```json
{
  "data": {
    "executeDummy3": [
      {
        "col1": 10,
        "col2": 20
      },
      {
        "col1": 30,
        "col2": 40
      }
    ]
  }
}
```

**Comment by yorek** [comment]
Thanks, that makes sense. The error I got wasn't helping and I thought it was a bug, but it really isn't. Same goes for the first problem mentioned in this issue, stored procedures without any resultset works perfectly fine. Definitely a mention to the documentation is needed.
