### ISSUE TITLE
[Bug]: Splitting actions for the same role results in a 'Unauthorized due to one or more fields in this mutation.'

### ISSUE THREAD

**Issue by MrMossevig** [Azure/data-api-builder#1987]
### What happened?

We have an entity (projects) that we want to have different policies for different actions. Ideally this is what we want to have:
```
"entities": {
    "Plan": {
      "source": "dbo.Project",
      "permissions": [
        {
          "actions": ["create", "update", "read"],
          "role": "authenticated",
          "policy": {
            "database": "@claims.UserId eq @item.OwnerId"
          }
        },
        {
          "actions": ["delete"],
          "role": "authenticated",
          "policy": {
            "database": "@claims.UserId eq @item.OrgOwnerId"
          }
        }
      ]
    }
}
```
This will result in the response:
```
{
    "errors": [
        {
            "message": "Unauthorized due to one or more fields in this mutation.",
            "extensions": {
                "code": "AuthorizationCheckFailed"
            }
        }
    ],
    "data": {
        "createPlan": null
    }
}
```

The problem comes when splitting actions between the same role, just by moving one action to another entry without policies, like this, will result in the same error:
```
"entities": {
    "Plan": {
      "source": "dbo.Project",
      "permissions": [
        {
          "actions": ["create", "update", "read"],
          "role": "authenticated"
        },
        {
          "actions": ["delete"],
          "role": "authenticated"
        }
      ]
    }
}
```

The error from the server running this locally is shown below

### Version

1.1.6

### What database are you using?

Azure SQL

### What hosting model are you using?

Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

GraphQL

### Relevant log output

```Text
[dataApi] info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
[dataApi]       Request starting HTTP/1.1 POST http://localhost:4280/graphql application/json 2728
[dataApi] info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
[dataApi]       Executing endpoint 'Hot Chocolate GraphQL Pipeline'
[dataApi] fail: Azure.DataApiBuilder.Service.Startup[0]
[dataApi]       A GraphQL request execution error occurred.
[dataApi]       Azure.DataApiBuilder.Service.Exceptions.DataApiBuilderException: Unauthorized due to one or more fields in this mutation.
[dataApi]          at Azure.DataApiBuilder.Core.Resolvers.SqlMutationEngine.AuthorizeMutationFields(IMiddlewareContext context, IDictionary`2 parameters, String entityName, EntityActionOperation mutationOperation) in /_/src/Core/Resolvers/SqlMutationEngine.cs:line 1034
[dataApi]          at Azure.DataApiBuilder.Core.Resolvers.SqlMutationEngine.ExecuteAsync(IMiddlewareContext context, IDictionary`2 parameters) in /_/src/Core/Resolvers/SqlMutationEngine.cs:line 98
[dataApi]          at Azure.DataApiBuilder.Core.Services.ResolverMiddleware.InvokeAsync(IMiddlewareContext context) in /_/src/Core/Services/ResolverMiddleware.cs:line 77
[dataApi]          at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
[dataApi]          at HotChocolate.AspNetCore.Authorization.AuthorizeMiddleware.InvokeAsync(IDirectiveContext context)
[dataApi]          at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
[dataApi]          at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
[dataApi]          at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
[swa] POST http://localhost:4280/graphql - 200
[dataApi] info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
[dataApi]       Executed endpoint 'Hot Chocolate GraphQL Pipeline'
[dataApi] info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
[dataApi]       Request finished HTTP/1.1 POST http://localhost:4280/graphql application/json 2728 - 200 - application/json;+charset=utf-8 108.3249ms
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrMossevig** [comment]
If anyone ends up here, the workaround that we're currently using is to create two separate entities towards the same table:
```
"entities": {
    "Plan": {
      "source": "dbo.Project",
      "permissions": [
        {
          "actions": ["create", "update", "read"],
          "role": "authenticated",
          "policy": {
            "database": "@claims.UserId eq @item.OwnerId"
          }
        }
      ]
    },
 "DeletePlan": {
      "source": "dbo.Project",
      "permissions": [
        {
          "actions": ["delete"],
          "role": "authenticated",
          "policy": {
            "database": "@claims.UserId eq @item.OrgOwnerId"
          }
        }
      ]
    }
}
```
And then using the DeletePlan-entity/mutation for delete operations.

**Comment by MrMossevig** [comment]
Okay, so after a lot of digging I realized that splitting actions was supposed to done in the actions array:
```
"entities": {
    "Plan": {
      "source": "dbo.Project",
      "permissions": [
        {
          "role": "authenticated",
          "actions": [
            {
              "action": "create",
              "policy": {
                "database": "@claims.userId eq @item.OwnerId"
              }
            },
            {
              "action": "read",
              "policy": {
                "database": "@claims.userId eq @item.OwnerId"
              }
            },
            {
              "action": "update",
              "policy": {
                "database": "@claims.userId eq @item.OwnerId"
              }
            },
            {
              "action": "delete",
              "policy": {
                "database": "@claims.UserId eq @item.OrgOwnerId"
              }
            }
          ]
        }
      ]
    }
}
```
