### ISSUE TITLE
[Bug]: MSSQL pipeline Flakey

### ISSUE THREAD

**Issue by seantleonard** [Azure/data-api-builder#2010]
### What happened?

MSSQL pipeline is flakely , typically in Linux tests, but sometimes windows, where all integration tests pass, but there is either a timeout or connection forcibly closed error. There may be a memory leak or inefficient use of resources occuring in test fixture which should be identified and remediated.

Why this is impactful:
1. Affects iteration velocity -> may allow quicker pace of merges because pipeline execution speed may be increased due to this and multiple runs don't need to be triggered

### Version

latest `main`

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

REST

### Relevant log output

```Text
Windows:

Passed!  - Failed:     0, Passed:  1010, Skipped:     2, Total:  1012, Duration: 11 m 55 sTest Run Aborted with error System.Exception: One or more errors occurred.
 ---> System.Exception: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Exception: An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Sockets.NetworkStream.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---.
 - Azure.DataApiBuilder.Service.Tests.dll (net6.0)
##[error]Error: The process 'C:\hostedtoolcache\windows\dotnet\dotnet.exe' failed with exit code 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
[current] I'm adding some more diagnostics (via dotnet test --diagto try and identify the issue in addition to having :
Public GitHub issues([1](https://github.com/microsoft/vstest/issues/2261), [2](https://github.com/microsoft/vstest/issues/4376), [3](https://github.com/microsoft/vstest/issues/2952)) range from incorrect async function declarations, test machine OOM, and/or other code defects. 
Issue is not consistent and pipeline takes 20-30 moinutes to execute. ( i briefly looked at what tests could be modified to improve test execution times, but that is a larger effor that may not fit within GA timeframe, so i stopped that line of investigation currently.)

**Comment by aaronburtle** [comment]
The following tests are flakey and have been ignored until we have a fix to make them consistently passing. The issue seems related to a possible race condition associated with hot-reloading in the test pipeline. More investigation needed to find the fix.

`ValidateAuthorizationResolver_HotReload`

`ComprehensiveHealthEndpoint_ValidateContents`

**Comment by sezal98** [comment]
The following tests are flakey and have been ignored until we have a fix to make them consistently passing. The issue seems related to a possible race condition associated with hot-reloading in the test pipeline. More investigation needed to find the fix.

Hot-reload runtime paths
ConfigurationTests.ValidateLogFilters
HotReloadConfigConnectionString

**Comment by Aniruddh25** [comment]
More and more hot reload configuration tests have been failing. See the pipeline logs at: https://dev.azure.com/sqldab/Data%20API%20builder%20Dependency%20Packages/_build/results?buildId=10837&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=f2696cc9-a35b-5158-31dc-9689759fe573&s=96ac2280-8cb4-5df5-99de-dd2da759617d 

Failed at 3 tests: 
`HotReloadConfigUpdateMappings`
`HotReloadConfigAddEntity`
`HotReloadEntityGQLEnabledFlag`

These have now been marked as Ignore in PR #2348

**Comment by aaronburtle** [comment]
Failed test:
`ValidateLocationHeaderFieldForPostRequests()` with display name = `Location Header validation - Stored Procedures, Base Route not configured`

Ignore as a part of PR https://github.com/Azure/data-api-builder/pull/2619
